#!/usr/bin/env python3
"""
CIVIL → OPA/Rego Transpiler

Converts a CIVIL DSL YAML module to an OPA/Rego policy file.

This transpiler is specialized for CIVIL modules that follow the SNAP eligibility
pattern: income threshold tables, deduction chains, and gross/net income tests.
It handles the CIVIL v1 limitation of no intermediate variable binding by
implementing the full deduction chain directly in Rego.

Usage:
    python tools/transpile_to_opa.py <civil_yaml> <output_rego>

Example:
    python tools/transpile_to_opa.py specs/ruleset/snap_eligibility.civil.yaml output/ruleset/snap_eligibility.rego

Exit codes:
    0 — success
    1 — error (message printed to stderr)
"""

import sys
import os
import yaml


def fail(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def load_civil(path):
    try:
        with open(path) as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        fail(f"File not found: {path}")
    except yaml.YAMLError as e:
        fail(f"YAML parse error: {e}")


def validate_before_transpile(path):
    """Run the CIVIL validator first. Exits 1 if invalid."""
    validator = os.path.join(os.path.dirname(__file__), "validate_civil.py")
    ret = os.system(f"python {validator} {path} > /dev/null 2>&1")
    if ret != 0:
        # Re-run with output visible
        os.system(f"python {validator} {path}")
        fail(f"CIVIL validation failed for {path}. Fix errors above before transpiling.")


def table_to_rego_dict(table_name, table_def, value_col):
    """Emit a Rego object literal from a CIVIL table."""
    rows = table_def.get("rows", [])
    key_col = table_def.get("key", [])[0]
    lines = [f"{table_name} := {{"]
    for row in rows:
        key = row[key_col]
        val = row[value_col]
        lines.append(f"    {key}: {val},")
    lines.append("}")
    return "\n".join(lines)


def transpile_snap(doc, output_path):
    """
    Transpile the SNAP CIVIL module to OPA/Rego.

    The net income calculation requires multi-step arithmetic where each
    deduction depends on income remaining after prior deductions. This cannot
    be expressed in CIVIL v1's `when:` expressions (no intermediate variables),
    so we implement it fully in Rego here.
    """
    tables = doc.get("tables", {})
    constants = doc.get("constants", {})

    # Extract table data
    gross_limits = tables.get("gross_income_limits", {})
    net_limits = tables.get("net_income_limits", {})
    std_deds = tables.get("standard_deductions", {})

    gross_rows = {r["household_size"]: r["max_gross_monthly"] for r in gross_limits.get("rows", [])}
    net_rows = {r["household_size"]: r["max_net_monthly"] for r in net_limits.get("rows", [])}
    std_rows = {r["household_size"]: r["deduction_amount"] for r in std_deds.get("rows", [])}

    # Extract constants
    shelter_cap = constants.get("SHELTER_DEDUCTION_CAP", 744)
    earned_rate = constants.get("EARNED_INCOME_DEDUCTION_RATE", 0.20)
    shelter_rate = constants.get("SHELTER_EXCESS_THRESHOLD_RATE", 0.50)
    gross_incr = constants.get("GROSS_INCOME_INCREMENT_9PLUS", 596)
    net_incr = constants.get("NET_INCOME_INCREMENT_9PLUS", 459)

    # Build Rego
    lines = [
        f"# Generated by tools/transpile_to_opa.py from {os.path.basename(sys.argv[1])}",
        f"# Module: {doc.get('module')}",
        f"# Description: {doc.get('description')}",
        f"# Version: {doc.get('version')}",
        f"# Effective: {doc.get('effective', {}).get('start')} – {doc.get('effective', {}).get('end')}",
        "#",
        "# DO NOT EDIT — regenerate with:",
        "#   python tools/transpile_to_opa.py specs/ruleset/snap_eligibility.civil.yaml output/ruleset/snap_eligibility.rego",
        "",
        "package snap.eligibility",
        "",
        "import future.keywords.if",
        "import future.keywords.contains",
        "",
        "# =============================================================================",
        "# FY2026 INCOME THRESHOLDS (from CIVIL tables)",
        "# =============================================================================",
        "",
    ]

    # Gross income limits dict
    lines.append("# Gross income limits: 130% FPL monthly (7 CFR § 273.9(a)(1))")
    lines.append("gross_income_limits := {")
    for size in sorted(gross_rows):
        lines.append(f"    {size}: {gross_rows[size]},")
    lines.append("}")
    lines.append("")

    # Net income limits dict
    lines.append("# Net income limits: 100% FPL monthly (7 CFR § 273.9(a)(2))")
    lines.append("net_income_limits := {")
    for size in sorted(net_rows):
        lines.append(f"    {size}: {net_rows[size]},")
    lines.append("}")
    lines.append("")

    # Standard deductions dict
    lines.append("# Standard deductions by household size (7 CFR § 273.9(c))")
    lines.append("standard_deductions := {")
    for size in sorted(std_rows):
        lines.append(f"    {size}: {std_rows[size]},")
    lines.append("}")
    lines.append("")

    lines += [
        "# =============================================================================",
        "# INCOME THRESHOLD LOOKUPS (with size 9+ formula fallback)",
        "# =============================================================================",
        "",
        "# Gross income limit for this household",
        "gross_limit := gross_income_limits[input.household_size] if {",
        "    input.household_size <= 8",
        f"}} else := {gross_rows[8]} + (input.household_size - 8) * {gross_incr}",
        "",
        "# Net income limit for this household",
        "net_limit := net_income_limits[input.household_size] if {",
        "    input.household_size <= 8",
        f"}} else := {net_rows[8]} + (input.household_size - 8) * {net_incr}",
        "",
        "# Standard deduction for this household (size 7+ same as size 6)",
        "standard_deduction := standard_deductions[input.household_size] if {",
        "    input.household_size <= 6",
        f"}} else := {std_rows[6]}",
        "",
        "# =============================================================================",
        "# DEDUCTION CHAIN (7 CFR § 273.9(b)–(d))",
        "# Applied in order; each step depends on income remaining after prior steps.",
        "# =============================================================================",
        "",
        "# Deduction 1: 20% of earned income (7 CFR § 273.9(b))",
        f"earned_income_deduction := input.earned_income * {earned_rate}",
        "",
        "# Deduction 2: Standard deduction (applied after earned income deduction)",
        "# (uses standard_deduction rule above)",
        "",
        "# Deduction 3: Dependent care deduction (7 CFR § 273.9(d)(4))",
        "dependent_care_deduction := input.dependent_care_costs",
        "",
        "# Income remaining after deductions 1, 2, 3 (base for shelter excess calculation)",
        "income_after_prior_deductions := input.gross_monthly_income",
        "    - earned_income_deduction",
        "    - standard_deduction",
        "    - dependent_care_deduction",
        "",
        "# Deduction 4: Excess shelter deduction (7 CFR § 273.9(d)(6))",
        f"shelter_excess := max([0, input.shelter_costs_monthly - ({shelter_rate} * income_after_prior_deductions)])",
        "",
        "# Shelter cap: $744/month unless elderly or disabled member (no cap)",
        "default is_exempt_household := false",
        "is_exempt_household if { input.has_elderly_member == true }",
        "is_exempt_household if { input.has_disabled_member == true }",
        "",
        f"shelter_deduction := shelter_excess if {{ is_exempt_household }} else := min([shelter_excess, {shelter_cap}])",
        "",
        "# Final net income",
        "net_income := income_after_prior_deductions - shelter_deduction",
        "",
        "# =============================================================================",
        "# INCOME TESTS",
        "# =============================================================================",
        "",
        "# Gross income test: non-exempt households must pass",
        "# default false: OPA boolean rules are undefined (not false) when conditions don't match",
        "default passes_gross_test := false",
        "passes_gross_test if { is_exempt_household }",
        "passes_gross_test if {",
        "    not is_exempt_household",
        "    input.gross_monthly_income <= gross_limit",
        "}",
        "",
        "# Net income test: all households must pass",
        "default passes_net_test := false",
        "passes_net_test if { net_income <= net_limit }",
        "",
        "# =============================================================================",
        "# ELIGIBILITY DECISION",
        "# =============================================================================",
        "",
        "default eligible := false",
        "",
        "eligible if {",
        "    passes_gross_test",
        "    passes_net_test",
        "}",
        "",
        "# denial_reasons: collected from failing tests",
        "denial_reasons contains reason if {",
        "    not passes_gross_test",
        '    reason := {',
        '        "code": "GROSS_INCOME_EXCEEDS_LIMIT",',
        '        "message": "Gross monthly income exceeds 130% of the Federal Poverty Level for this household size",',
        '        "citation": "7 CFR § 273.9(a)(1)"',
        "    }",
        "}",
        "",
        "denial_reasons contains reason if {",
        "    passes_gross_test",
        "    not passes_net_test",
        '    reason := {',
        '        "code": "NET_INCOME_EXCEEDS_LIMIT",',
        '        "message": "Net monthly income after allowable deductions exceeds 100% of the Federal Poverty Level for this household size",',
        '        "citation": "7 CFR § 273.9(a)(2)"',
        "    }",
        "}",
        "",
        "# =============================================================================",
        "# STRUCTURED DECISION OBJECT",
        "# =============================================================================",
        "",
        "decision := {",
        '    "eligible": eligible,',
        '    "denial_reasons": [r | r := denial_reasons[_]],',
        '    "computed": {',
        '        "gross_monthly_income": input.gross_monthly_income,',
        '        "gross_limit": gross_limit,',
        '        "passes_gross_test": passes_gross_test,',
        '        "earned_income_deduction": earned_income_deduction,',
        '        "standard_deduction": standard_deduction,',
        '        "dependent_care_deduction": dependent_care_deduction,',
        '        "shelter_deduction": shelter_deduction,',
        '        "net_income": net_income,',
        '        "net_limit": net_limit,',
        '        "passes_net_test": passes_net_test',
        "    }",
        "}",
    ]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"✓ Transpiled to {output_path}")


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <civil_yaml> <output_rego>", file=sys.stderr)
        sys.exit(1)

    civil_path = sys.argv[1]
    output_path = sys.argv[2]

    validate_before_transpile(civil_path)
    doc = load_civil(civil_path)
    transpile_snap(doc, output_path)


if __name__ == "__main__":
    main()
